import img from './../TeamHeader/coord-1.png'

export const Executive_Team = [
    {
        index: 0,
        image: img,
        name: "Raheena Bin Mohd.",
        post: "General Secratory",
        instaUrl: "#",
        linkdUrl: "#",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. dummy text of the printing and typesetting industry."
    },
    {
        index: 1,
        image: img,
        name: "Vivek Pandey",
        post: "Asst. General Secratory",
        instaUrl: "#",
        linkdUrl: "#",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. dummy text of the printing and typesetting industry."
    },
    {
        index: 2,
        image: img,
        name: "Hrittika Hajari",
        post: "Asst. General Secratory",
        instaUrl: "#",
        linkdUrl: "#",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. dummy text of the printing and typesetting industry."
    },
]

export const Social_Team = [
    {
        index: 0,
        image: img,
        name: "Tanmay Shree",
        post: "Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 1,
        image: img,
        name: "Abhudhya Kumar",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 2,
        image: img,
        name: "Rakshita",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 3,
        image: img,
        name: "Madhumita Moi",
        post: "Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 4,
        image: img,
        name: "Triasha Roy",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 5,
        image: img,
        name: "Hrittika Hajari",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 6,
        image: img,
        name: "Eshita Bhattacharjee",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
]



export const Editorial_Team = [
    {
        index: 0,
        image: img,
        name: "Kajal Kumari",
        post: "Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 1,
        image: img,
        name: "Eshita Bhattacharjee",
        post: "Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 2,
        image: img,
        name: "Hrittika Hajari",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 3,
        image: img,
        name: "Dayita Chaudhuri",
        post: "Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 4,
        image: img,
        name: "Sourajita Chanda",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 5,
        image: img,
        name: "Akshit Parikh",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 6,
        image: img,
        name: "Siddharthan Dileep",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 7,
        image: img,
        name: "Isha Tripathi",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 8,
        image: img,
        name: "M. Mahesh",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 9,
        image: img,
        name: "Advait Girap",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 10,
        image: img,
        name: "Triasha Roy",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 11,
        image: img,
        name: "Anjura Vundi",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 12,
        image: img,
        name: "Shreyashi Das",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
]


export const Graphics_Team = [
    {
        index: 0,
        image: img,
        name: "Aman Priyadarshi",
        post: "Graphics Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 1,
        image: img,
        name: "Akshat Verma",
        post: "Technical Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 2,
        image: img,
        name: "Ankit Gautam",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 3,
        image: img,
        name: "Tanmay Shree",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 4,
        image: img,
        name: "Tirthankar Acharya",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
]


export const Debating_Team = [
    {
        index: 0,
        image: img,
        name: "Vivek Pandey",
        post: "Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 1,
        image: img,
        name: "Raheena Bin Mohd.",
        post: "Technical Lead",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 2,
        image: img,
        name: "Triasha Roy",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 3,
        image: img,
        name: "Dharun Shankar",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 4,
        image: img,
        name: "Isha Tripathi",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 5,
        image: img,
        name: "Kajal Kumari",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 6,
        image: img,
        name: "Akshit Parikh",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 7,
        image: img,
        name: "Advait Girap",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
    {
        index: 8,
        image: img,
        name: "Sumit Kumar",
        post: "Member",
        instaUrl: "#",
        linkdUrl: "#",
    },
]